### ISSUE TITLE
请问SSLException怎么解

### ISSUE THREAD

**Issue by ghbhaha** [leancloud/leanengine-java-sdk#4]
09:41:51.246 [OkHttp https://app-router.leancloud.cn/1/route?appId=g7xtg14drztldjnc0sbcorkwz1ki745ux1jenmy90n1z1v5w] ERROR com.avos.avoscloud.AVOSCloud - get router error err:com.avos.avoscloud.AVException: javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException
com.avos.avoscloud.AVException: javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException
        at com.avos.avoscloud.AppRouterManager$1.onFailure(AppRouterManager.java:187)
        at com.avos.avoscloud.GenericObjectCallback.onFailure(GenericObjectCallback.java:16)
        at com.avos.avoscloud.GetHttpResponseHandler.onFailure(GetHttpResponseHandler.java:128)
        at com.avos.avoscloud.AsyncHttpResponseHandler.onFailure(AsyncHttpResponseHandler.java:35)
        at com.avos.avoscloud.okhttp.Call$AsyncCall.execute(Call.java:174)
        at com.avos.avoscloud.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: java.security.ProviderException: java.security.KeyException
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1378)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
        at com.avos.avoscloud.okhttp.Connection.connectTls(Connection.java:240)
        at com.avos.avoscloud.okhttp.Connection.connectSocket(Connection.java:202)
        at com.avos.avoscloud.okhttp.Connection.connect(Connection.java:173)
        at com.avos.avoscloud.okhttp.Connection.connectAndSetOwner(Connection.java:359)
        at com.avos.avoscloud.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:117)
        at com.avos.avoscloud.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.avos.avoscloud.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
        at com.avos.avoscloud.okhttp.Call.getResponse(Call.java:274)
        at com.avos.avoscloud.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
        at com.avos.avoscloud.okhttp.Call.getResponseWithInterceptorChain(Call.java:194)
        at com.avos.avoscloud.okhttp.Call.access$100(Call.java:32)
        at com.avos.avoscloud.okhttp.Call$AsyncCall.execute(Call.java:160)
        ... 4 more
Caused by: java.security.ProviderException: java.security.KeyException
        at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:146)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:704)
        at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:78)
        at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:717)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:278)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:849)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1035)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1344)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
        ... 17 more

**Comment by sdjcw** [comment]
你好，请问下这个异常是什么情况下产生的？

**Comment by ghbhaha** [comment]
发布在国外的vps上就有这个问题

**Comment by sdjcw** [comment]
你好，这个 java lib 是使用在我们 云引擎 运行环境的，也就是运行环境是 LeanCloud 提供的。
我没太明白你说的 “发布在国外的 vps” 是什么意思。

**Comment by ghbhaha** [comment]
发布在国外的服务器出错

**Comment by sdjcw** [comment]
你好，这个 lib 是为运行在 LeanCloud 云引擎环境提供一些辅助 api，所以部署在自建服务器上可能会遇到问题。

**Comment by lbt05** [comment]
请仔细检查一下日志，是否只有访问 https://app-router.leancloud.cn/1/route? 节点才有SSL的异常
